const supported=new Set('md txt rst html xhtml epub pdf png jpg jpeg tif tiff bmp webp docx odt rtf xlsx ods csv tsv pptx odp doc dot xls xlt ppt pot docm xlsm pptm'.split(' '));
const native=window.__TAURI__;let queue=[],running=false,stopped=false;
const $=id=>document.getElementById(id),ext=f=>(f.name.split('.').pop()||'').toLowerCase();
function render(){const el=$('queue');el.replaceChildren();if(!queue.length){const li=document.createElement('li');li.className='muted';li.textContent='No files selected.';el.append(li);return}queue.forEach((x,i)=>{const li=document.createElement('li');li.className='row';const n=document.createElement('span');n.textContent=`${i+1}. ${x.path}`;const s=document.createElement('span');s.textContent=x.status+(x.supported===false?' — unsupported':'');li.append(n,s);el.append(li)})}
function addBrowser(files){const seen=new Set(queue.map(x=>x.key));for(const f of files){const key=f.webkitRelativePath||f.name+'|'+f.size+'|'+f.lastModified;if(!seen.has(key)){queue.push({f,key,path:f.webkitRelativePath||f.name,status:'queued',supported:supported.has(ext(f))});seen.add(key)}}queue.sort((a,b)=>a.path.localeCompare(b.path));render()}
function browserStub(x){return `<!-- Phase 1 scaffold: adapter stub; not a real conversion -->\n\n# Conversion pending\n\nSource: \`${x.path}\`\n\nNo engine is configured. This placeholder is for demo fixtures only.\n`}
async function browserStart(){if(running||!queue.length)return;running=true;stopped=false;$('start').disabled=true;$('stop').disabled=false;for(const x of queue){if(stopped)break;x.status='processing';render();await new Promise(r=>setTimeout(r,20));if(!x.supported){x.status='unsupported';continue}x.url=URL.createObjectURL(new Blob([browserStub(x)],{type:'text/markdown'}));x.status='stub placeholder — click row to Reveal';render()}running=false;$('start').disabled=false;$('stop').disabled=true}
let nativeFiles=[],nativeFolders=[];async function nativePlan(){const rows=await native.core.invoke('plan_queue',{files:nativeFiles,folders:nativeFolders,chosenOutput:$('outputStatus').dataset.path||null});queue=rows.map(x=>({path:x.path,output:x.output,status:x.supported?'queued':'unsupported',supported:x.supported}));render()}async function nativeChoose(kind){const picked=await native.dialog.open({multiple:true,directory:kind==='folder'});const values=picked?(Array.isArray(picked)?picked:[picked]):[];if(kind==='folder')nativeFolders.push(...values);else nativeFiles.push(...values);await nativePlan()}
async function nativeStart(){if(running||!queue.length)return;running=true;$('start').disabled=true;$('stop').disabled=false;const rows=await native.core.invoke('convert_queue',{paths:queue.map(x=>x.path),outputs:queue.map(x=>x.output)});rows.forEach((r,i)=>{queue[i].status=r.status;queue[i].output=r.output||queue[i].output});render();running=false;$('start').disabled=false;$('stop').disabled=true}
function wireCommon(){ $('clear').onclick=()=>{queue=[];render()};$('queue').onclick=e=>{const i=Number(e.target.closest('li')?.textContent?.split('.')[0])-1,x=queue[i];if(x?.url){const a=document.createElement('a');a.href=x.url;a.download=x.f.name.replace(/\.[^.]+$/,'')+'.md';a.click()}else if(native&&x?.output&&native.opener)native.opener.openPath(x.output)} }
if(native){$('notice').textContent='Native Tauri mode: local dialogs and writes; Phase 1 placeholders only.';$('chooseFiles').onclick=()=>nativeChoose('file');$('chooseFolder').onclick=()=>nativeChoose('folder');$('start').onclick=nativeStart;$('stop').onclick=async()=>{stopped=true;await native.core.invoke('cancel');running=false;$('start').disabled=false;$('stop').disabled=true};$('pickOutput').disabled=false;$('pickOutput').onclick=async()=>{const p=await native.dialog.open({directory:true,multiple:false});if(p){$('chosenDest').checked=true;$('outputStatus').dataset.path=p;$('outputStatus').textContent=' Selected: '+p}}}else{$('notice').textContent='Browser preview only: outputs download; native shell required for source/output paths.';$('chooseFiles').onclick=()=>$('files').click();$('chooseFolder').onclick=()=>$('folder').click();$('files').onchange=e=>addBrowser(e.target.files);$('folder').onchange=e=>addBrowser(e.target.files);$('start').onclick=browserStart;$('stop').onclick=()=>{stopped=true};$('pickOutput').disabled=true;$('outputStatus').textContent=' Native shell required for chosen-folder writes';$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();addBrowser(e.dataTransfer.files)}}wireCommon();render();
if(native)$('clear').addEventListener('click',()=>{nativeFiles=[];nativeFolders=[]});
if(native?.event?.listen){native.event.listen('tauri://drag-drop',async e=>{const paths=(e.payload?.paths||e.payload||[]).filter(p=>typeof p==='string');for(const p of paths){if(nativeFiles.includes(p)||nativeFolders.includes(p))continue;try{const meta=await native.core.invoke('path_kind',{path:p});(meta==='folder'?nativeFolders:nativeFiles).push(p)}catch{nativeFiles.push(p)}}await nativePlan()})}
